"""empty message

Revision ID: 87368bf06d3f
Revises: 936a99236716
Create Date: 2016-12-13 13:30:29.414389

"""

# revision identifiers, used by Alembic.
revision = '87368bf06d3f'
down_revision = '936a99236716'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('analysis_score', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'analysis_score')
    ### end Alembic commands ###
